# Generated by Django 4.1.4 on 2023-03-17 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recorrencia',
            name='pedido_pgmto',
        ),
    ]
