# Generated by Django 4.1.4 on 2023-03-20 16:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_excelfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='excelfile',
            name='title',
            field=models.CharField(default=None, max_length=80),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='excelfile',
            name='upload_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='excelfile',
            name='file',
            field=models.FileField(upload_to=''),
        ),
    ]
