# Generated by Django 4.1.4 on 2023-03-20 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_excelfile_title_excelfile_upload_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recorrencia',
            name='n_pedido',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
