# Generated by Django 4.1.4 on 2023-03-20 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_recorrencia_n_pedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='excelfile',
            name='processed',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
