# Generated by Django 4.1.4 on 2023-07-06 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_excelfile_processed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku_nome', models.CharField(max_length=128)),
                ('sku_ref', models.CharField(max_length=16, unique=True)),
                ('sku_url', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='recorrencia',
            name='produtos',
            field=models.ManyToManyField(blank=True, default='', to='api.produto'),
        ),
    ]
