# Generated by Django 4.1.4 on 2023-07-07 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_produto_recorrencia_produtos'),
    ]

    operations = [
        migrations.AddField(
            model_name='excelfile',
            name='file_type',
            field=models.CharField(default='cadastro', max_length=16),
        ),
    ]
