# Generated by Django 4.1.4 on 2023-07-19 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_produto_recorrencia_produtos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente_CPF_CNPJ', models.BigIntegerField()),
                ('nome_razao_social', models.CharField(max_length=128)),
                ('pedidos', models.ManyToManyField(blank=True, to='api.recorrencia')),
            ],
        ),
    ]
