# Generated by Django 4.1.4 on 2023-07-19 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_cliente'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cliente',
        ),
    ]
